import { Inter } from 'next/font/google'
import './globals.css'
import Header from './ui/Header'
import Sidenav from './ui/Sidenav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + ' flex flex-col'}>
        <Header />
        <div className={`flex grow w-full`}>
          <Sidenav />
          <div className='p-2 w-full h-full'>
            {children}
          </div>
        </div>

      </body>
    </html>
  )
}
